name: CI/CD Pipeline
on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build and push config-server image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-configserver ./configserver
          docker push ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-configserver

      - name: Build and push discovery-server image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-discoveryserver ./discoveryserver
          docker push ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-discoveryserver          

      - name: Build and push gateway-server image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-gatewayserver ./gatewayserver
          docker push ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-gatewayserver

      - name: Build and push customer-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-customerservice ./customerservice
          docker push ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-customerservice

      - name: Build and push invoice-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-invoiceservice ./invoiceservice
          docker push ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-invoiceservice

      - name: Build and push order-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-orderservice ./orderservice
          docker push ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-orderservice

      - name: Build and push product-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-productservice ./productservice
          docker push ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-productservice

      - name: Build and push auth-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-authservice ./authservice
          docker push ${{ secrets.DOCKER_USERNAME }}/turkcell-pair1-authservice