name: Publish common package to Github packages
on:
  push:
    - 'common/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Publish package
        run: mvn deploy -pl common
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}